### ISSUE TITLE
Short paper workplan

### ISSUE THREAD

**Issue by cclatterbuck** [cclatterbuck/CAplastics#1]
CCD = coastal cleanup day data
OC = ocean conservancy data

**Research questions**:
1. What plastics are most commonly collected in California?
    - pre-processing: 
        - think about whether/how to include 2021 data; whether/how to account for missing data for 2020
        - merge CCD & OC datasets so that the same categories are available in each year (e.g., create aggregate categories for later years where items were split into smaller subcategories).
    - Show:
        - total collected overall
        - frequency on top-10 list
        - normalized counts (based on OC data since 2016 alone)
    - Show that within the aggregate categories, plastics > all other material types collected (maybe for appendix?)
2. Have the commonly collected plastic types changed over time?
    - Determine whether top 20? ranks have changed over time -- something like rank order stability analysis?
        - Determine for both overall & normalized counts
    - Needs to account for pre-processing step above
3. Do commonly collected plastic types vary geographically:
    - Coastal vs inland counties? A NorCal vs. SoCal rivalry?
    - GIS to determine other coastal vs. inland attributes (e.g., mileage from coast, etc.)

**Comment by cclatterbuck** [comment]
Additional analyses and visualizations:

- [ ] Timeseries of OC data, look for any increases or decreases in collected items over time (normalized data)
- [ ] Compare plastic type hotspots to CES 4.0 data -- Scott noted it may take time to access this data
- [ ] R Shiny bubble plot of total items & breakdown by major plastic types (normalized data)
